Validate application names so that API calls and Docker build doesn't…
meroxa/cli pull request #296
Opened 2022-03-31 21:00 UTC by janelletavares

… fail later

## Description of change

Fixes https://github.com/meroxa/turbine-project/issues/108

## Type of change

- [ ]  New feature
- [ ]  Bug fix
- [ ]  Refactor
- [ ]  Documentation

## How was this tested?

- [ ]  Unit Tests
- [ ]  Tested in staging

## Demo
![Screenshot from 2022-03-31 13-30-48](https://user-images.githubusercontent.com/12731615/161148530-e4048603-3c84-4ed0-a5c4-66e5648d8b5a.png)
![Screenshot from 2022-03-31 13-43-29](https://user-images.githubusercontent.com/12731615/161148539-03a99cbf-c914-4fd6-99ab-54bb77771052.png)

## Additional references

## Documentation updated

2022-04-01 05:15 UTC, raulb requested changes
@janelletavares a test would be nice 👼

2022-04-01 05:15 UTC, raulb commented on cmd/meroxa/root/apps/init.go
> +			"invaid application name: %s;"+
```suggestion
			"invalid application name: %s;"+
```

2022-04-01 23:40 UTC, janelletavares commented
> @janelletavares a test would be nice angel

you caught me ;-) not stealthy enough

2022-04-04 05:45 UTC, raulb approved these changes

2022-04-04 16:49 UTC, merged