Exit 1 when grpc requests fail (#771)
meroxa/cli pull request #774
Opened 2023-06-10 00:19 UTC by janelletavares

## Description of change

Fixes <GitHub Issue>

## Type of change

- [ ]  New feature
- [ ]  Bug fix
- [ ]  Refactor
- [ ]  Documentation

## How was this tested?

- [ ]  Unit Tests
- [ ]  Tested in staging
- [ ]  Tested in minikube

## Demo

| before | after |
|--------|-------|
|||

## Additional references

## Documentation updated

2023-06-13 11:47 UTC, raulb requested changes
Looks like after this change, `turbine.RunCmd` is no longer used. We should update tests to use `RunCmdWithErrorDetection` instead.

2023-06-13 13:31 UTC, janelletavares commented
@raulb thank you for looking. I will make the update.

2023-06-13 16:27 UTC, janelletavares commented
I would like to merge https://github.com/meroxa/turbine-go/pull/163 first so that new apps won't conflict with this CLI change

2023-06-14 10:07 UTC, raulb approved these changes

2023-06-14 15:56 UTC, merged